### ISSUE TITLE
CSS is broken

### ISSUE THREAD

**Issue by felipeshiratori** [thiagosanches/template-builder#7]
Dialog css is returning 404

**Comment by felipeshiratori** [comment]
This piece of code doesn't exist anymore:
https://github.com/thiagosanches/template-builder/blob/156bd23fed9640bfe71fd956f9f766ef2be281a8/InterfaceBuilder.Engine/Elements/Template.html#L8

are you clear now?

**Comment by thiagosanches** [comment]
Thanks for the update!
